[package]
name = "rust-exercise"
version = "0.1.0"
authors = ["MattrGlobal"]
edition = "2018"


[dependencies]
rocket = "0.4"
rocket_contrib = { version = "0.4", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
